plugins:
  - package: netlify-plugin-no-more-404
    config:
      on404: 'error'
      cacheKey: 'anystring' 
      preserveBuildIds: # compare vs specific build IDs to ensure no regression 
      - abc123
      - def345
      - ghi678
